"""
sentinel/agents/reporter.py

Report Agent.
Takes a completed ScanResult and produces:
1. A structured JSON report (machine-readable)
2. A human-readable Markdown report

NEVER:
- Suggests exploitation steps
- Includes working payloads
- Outputs attack code
"""

import json
from datetime import datetime, timezone
from pathlib import Path

def _now() -> datetime:
    return datetime.now(timezone.utc)

from sentinel.core.models import ScanResult, Finding, Severity


REPORTS_DIR = Path("reports")


def generate_report(result: ScanResult) -> dict:
    """
    Generate both JSON and Markdown reports.
    Returns dict with paths to both files.
    """
    REPORTS_DIR.mkdir(exist_ok=True)
    timestamp = _now().strftime("%Y%m%d_%H%M%S")
    base_name = f"sentinel_{result.session_id[:8]}_{timestamp}"

    json_path = REPORTS_DIR / f"{base_name}.json"
    md_path   = REPORTS_DIR / f"{base_name}.md"

    # Write JSON
    json_report = _build_json_report(result)
    with open(json_path, "w") as f:
        json.dump(json_report, f, indent=2, default=str)

    # Write Markdown
    md_content = _build_markdown_report(result)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"[REPORTER] Reports saved: {json_path}, {md_path}")
    return {
        "json_path": str(json_path),
        "md_path":   str(md_path),
        "json":      json_report,
        "markdown":  md_content,
    }


# ── JSON Report ───────────────────────────────────────────────────────────────

def _build_json_report(result: ScanResult) -> dict:
    return {
        "sentinel_report": {
            "version": "1.0",
            "generated_at": _now().isoformat(),
            "session_id": result.session_id,
            "target": result.target,
            "scan_mode": result.mode,
            "agents_run": [a.value for a in result.agents_run],
        },
        "summary": {
            "total_findings": result.total,
            "by_severity": result.by_severity,
            "executive_summary": result.summary,
        },
        "findings": [_finding_to_dict(f) for f in _sorted_findings(result.findings)],
        "pipeline_summary": getattr(result, 'pipeline_summary', {}),
        "negative_validations_count": getattr(result, 'negative_validations', 0),
        "disclaimer": (
            "This report was generated by Sentinel, a blue team vulnerability intelligence tool. "
            "All findings are for defensive purposes only. "
            "Do not use this report to exploit vulnerabilities. "
            "Ensure you have authorization to scan the target system."
        ),
    }


def _finding_to_dict(f: Finding) -> dict:
    return {
        "id":              f.finding_id,
        "severity":        f.severity,
        "title":           f.title,
        "description":     f.description,
        "agent":           f.agent,
        "file":            f.file_path,
        "line":            f.line_number,
        "cve":             f.cve_id,
        "mitre_tactic":    f.mitre_tactic,
        "mitre_technique": f.mitre_technique,
        "remediation":     f.remediation,
        "timestamp":       f.timestamp.isoformat(),
    }


# ── Markdown Report ───────────────────────────────────────────────────────────

def _build_markdown_report(result: ScanResult) -> str:
    lines = []

    lines.append("# 🛡️ Sentinel Security Report")
    lines.append(f"\n**Target:** `{result.target}`")
    lines.append(f"**Scan Mode:** `{result.mode}`")
    lines.append(f"**Session ID:** `{result.session_id}`")
    lines.append(f"**Generated:** {_now().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Agents Run:** {', '.join(a.value for a in result.agents_run)}")

    lines.append("\n---\n")

    # Summary
    lines.append("## Executive Summary")
    if result.summary:
        lines.append(f"\n{result.summary}")

    lines.append("\n### Finding Count by Severity\n")
    for severity in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
        count = result.by_severity.get(severity, 0)
        if count > 0:
            icon = _severity_icon(severity)
            lines.append(f"- {icon} **{severity}:** {count}")

    lines.append(f"\n**Total:** {result.total} findings")

    if result.total == 0:
        lines.append("\n✅ No findings detected.")
        lines.append(_disclaimer())
        return "\n".join(lines)

    lines.append("\n---\n")

    # Pipeline summary
    pipeline = getattr(result, 'pipeline_summary', {})
    if pipeline:
        lines.append("## Evidence Pipeline Summary\n")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Hypotheses tested | {pipeline.get('hypotheses_tested', 0)} |")
        lines.append(f"| Confirmed (with evidence) | {pipeline.get('confirmed_findings', 0)} |")
        lines.append(f"| Refuted (NOT vulnerable) | {pipeline.get('refuted_findings', 0)} |")
        lines.append(f"| Inconclusive | {pipeline.get('inconclusive', 0)} |")
        lines.append(f"| Confirmation rate | {pipeline.get('confirmation_rate', 0):.0%} |")
        lines.append(f"| Probes prevented (dedup) | {pipeline.get('probes_prevented', 0)} |")

        ag = pipeline.get('attack_graph', {})
        if ag:
            lines.append(f"| Attack chains active | {ag.get('active_chains', 0)} |")
            lines.append(f"| Attack chains complete | {ag.get('complete_chains', 0)} |")
            lines.append(f"| Chain intersections | {ag.get('intersections', 0)} |")
        lines.append("")

    lines.append("\n---\n")
    lines.append("## Findings\n")

    # Group by severity
    for severity in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
        severity_findings = [f for f in result.findings if f.severity == severity]
        if not severity_findings:
            continue

        icon = _severity_icon(severity)
        lines.append(f"### {icon} {severity} ({len(severity_findings)})\n")

        for i, finding in enumerate(severity_findings, 1):
            lines.append(f"#### {i}. {finding.title}")
            lines.append(f"\n**Agent:** `{finding.agent}`")
            if finding.file_path:
                loc = f"`{finding.file_path}`"
                if finding.line_number:
                    loc += f" line {finding.line_number}"
                lines.append(f"**Location:** {loc}")
            if finding.cve_id:
                lines.append(f"**CVE/ID:** `{finding.cve_id}`")
            if finding.mitre_tactic:
                tactic_str = finding.mitre_tactic
                if finding.mitre_technique:
                    tactic_str += f" → {finding.mitre_technique}"
                lines.append(f"**MITRE ATT&CK:** {tactic_str}")

            lines.append(f"\n**Description:**\n{finding.description}")

            if finding.remediation:
                lines.append(f"\n**Remediation:**\n{finding.remediation}")

            lines.append("\n---")

    lines.append(_disclaimer())
    return "\n".join(lines)


def _sorted_findings(findings: list[Finding]) -> list[Finding]:
    order = {
        Severity.CRITICAL: 0,
        Severity.HIGH:     1,
        Severity.MEDIUM:   2,
        Severity.LOW:      3,
        Severity.INFO:     4,
    }
    return sorted(findings, key=lambda f: order.get(f.severity, 5))


def _severity_icon(severity: Severity) -> str:
    return {
        Severity.CRITICAL: "🔴",
        Severity.HIGH:     "🟠",
        Severity.MEDIUM:   "🟡",
        Severity.LOW:      "🔵",
        Severity.INFO:     "⚪",
    }.get(severity, "⚪")


def _disclaimer() -> str:
    return (
        "\n\n---\n\n"
        "*This report was generated by Sentinel. "
        "All findings are for **defensive purposes only**. "
        "Do not use this report to exploit vulnerabilities. "
        "Ensure you have explicit authorization to test the target system.*"
    )
